[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
remappings = [
    "@inco/lightning/=node_modules/@inco/lightning/src/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
rise = "https://testnet.riselabs.xyz"
fhenix = "https://ethereum-sepolia-rpc.publicnode.com"
fhenix_arb = "https://sepolia-rollup.arbitrum.io/rpc"
inco = "https://sepolia.base.org"

[etherscan]
rise = { key = "placeholder", url = "https://explorer.testnet.riselabs.xyz/api" }
